### PR TITLE
fixes for noetic CMake build: removed unnecessary dependencies

### PR DESCRIPTION
**Pull request by davefeilseifer**
minor compile fixes for noetic development, should need new noetic-devel branch

### CODE REVIEW

**Comment by davefeilseifer** [comment]
this PR passes prerelease tests for focal/noetic, package release could happen after merge

**Comment by davefeilseifer** [comment]
@TheDash, this has been sitting for a while, is there a chance this could get merged soon? It should be an easy merge/release since it already passes prerelease tests

generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  noetic default ubuntu focal amd64 \
  --custom-repo \
    ros_realtime__custom-1:git:https://github.com/PR2-prime/ros_realtime.git:noetic-devel \
  --level 0 \
  --output-dir ./

**Comment by davefeilseifer** [comment]
@chadrockey this is another lingering pull, if you're able to help out here as well.

**Comment by chadrockey** [comment]
@tfoote I made a team for PR2 maintainers (and then may have immediately broke it by abdicating my spot).  Before we add @davefeilseifer I wanted to check with you since this is in the core ROS stacks.  Please add him with the appropriate permissions if you can.

This repo is probably also a candidate for being spun out or forked into a different PR2 specific organization.  I believe it’s been black listed from the build server and probably shouldn’t be considered core ROS functionality.

**Comment by tfoote** [comment]
It's fine for you to hand this off to @davefeilseifer 

I see the PR2 Maintainers team but it's now empty with only access to this repo. I'm going to clear it out since it's empty now. There's also a synonymous team for this repo so I've invited @davefeilseifer to that.

**Pull request merged**
